### ISSUE TITLE
[INFO] 소셜 로그인 진행 방식에 대한 논의

### ISSUE THREAD

**Issue by owonie** [meong-story/documents#1]
## 주제
소셜 로그인의 진행 흐름을 설계해야합니다. 인가코드를 어디에서 처리해줄지에 따라 방법이 달라집니다.

## 해당하는 부분
소셜 로그인 (Auth)

## 설명
소셜 로그인 프로세스는 두 가지 방식이 있어요.
  1. 프론트 -> 소셜 -> 프론트(인가코드) -> 백엔드 -> 프론트
  2. 프론트 -> 백엔드(인가코드) -> 소셜 -> 백엔드 -> 프론트

두 방식의 결정적인 차이는 소셜 로그인을 위한 인가코드 처리 시점입니다.
프론트 단에서 인가 코드를 받아 백엔드로 로그인 요청을 보낸다면 첫 번째 방법을, 
백엔드에서 모든 작업을 완수해준 뒤, 프론트로 리다이렉트를 처리해준다면 두 번째 방법을 선택할 수 있습니다.

## 추가사항
딱 정해져있는 구현 방식은 없지만, 설득력 있는 근거를 찾아 상황에 맞는 선택하면 좋을 듯 싶습니다 :)

**Comment by j2h30728** [comment]
## 제안

1번 안을 제안드립니다.
 
2번 안 (프론트 -> 백엔드(인가 코드) -> 소셜 -> 백엔드 -> 프론트)으로 진행할 경우, 
사용자에게 실시간 피드백을 주기가 어려워 사용자 경험이 저하됩니다. 
사용자가 클라이언트에서 사용자 인증 동의를 진행한 후, 로그인이 완료되어 토큰이 발급되는 동안 사용자에게 피드백을 제공하는 것이 필요합니다.

사용자 경험을 우선시하는 1번안을 제안드립니다. 
이 방법은 인증 후 사용자가 로딩 스피너를 통해 인증 진행 상태를 실시간으로 확인할 수 있게 하여, 사용자 경험을 개선합니다. 
인가 코드는 짧은 시간 동안만 유효한 일회용 코드이므로, 프론트엔드에서 인가 코드를 수신하고 이를 백엔드로 전달하는 방식이 실용적이라 생각됩니다.

**Comment by owonie** [comment]
## 논의

제안 확인했습니다. 논의 중 말씀하신 것 처럼 인가코드는 일회용으로 발급되기에, 보안적으로 안전하다고 판단할 수 있다고 생각이드네요. 

클라이언트에서 인가코드 추출 처리 역할을 가져간다면, 백엔드 쪽의 구현 복잡도도 낮아질 것으로 보입니다. 좋은 의견 감사합니다 :)
