### ISSUE TITLE
[ISSUE] petId 반환 방식에 대한 논의

### ISSUE THREAD

**Issue by owonie** [meong-story/documents#2]
## 주제
petId 값을 null로 보낼지, 아니면 null값일 때 response 객체 필드에서 빼버릴지  논의해보는게 좋아보여요.

## 해당하는 부분
유저 정보 조회 (User)

## 설명
유저 정보를 반환하는 api 요청에서, 반환 값 객체 내부에 petId 필드가 존재합니다. 갓 회원가입을 한 유저에겐 등록된 petId가 없는 케이스가 존재할 수 있습니다. 

## 함께 논의해야할 내용
해당 케이스를 처리할 수 있는 방법은 아래와 같습니다:
- DB에 저장되어있는 petId는 nullable 하기에, null 값을 클라이언트에게 반환하기. ( petId === null )
- JS 기반의 클라이언트에서 null 값을 객체로 인식하기에, 아예 반환 객체 필드에서 제외하기. ( PetId === undefined )

어떤 방식을 사용할지 함께 결정해보는게 좋을 것 같습니다 :)

**Comment by j2h30728** [comment]
## 논의 및 제안

해당 논의와 함께 **유저와 동물의 관계는 1 : 1인지, 1 : N 인지** 에 대한 논의가 필요해보입니다.
물론, 스웨거를 확인 한 바로는 1:1 로 확인되지만 현재 프론트엔드에서 공유한 기능명세서(피그잼)은 1 : N을 고려하여 작성되었기에 구분하여 말씀드립니다.

### 1) 1: 1 관계일 경우,

현재 명세서에서는 petId 가 string 으로 되어 있는 것은 유저와 동물의 관계는 1 : 1 관계로 보여집니다. 
단, 이를 선택할 경우 추후에 1 : N 관계로의 확장성이 어려울 것 같습니다.

유저 정보 조회에서는 petId를 string 직접 명시해주는 것보다는, 연결되어 있는 동물이 있는지 boolean 값을 사용하는 것이 어떨까요?
```json
{
  "message": "string",
  "name": "string",
  "imageUrl": "string",
  "isRegisteredPet":"boolean",
  "refreshToken": "string"
}

```
로그인 유저를 기반으로 pet 에 대한 정보를 조회할 것이기 때문에, 동물이 한 마리만 매칭 될 것이기 때문에 유저정보 조회에서 id값을 명시 해주지 않아도 될 것 같아 말씀드립니다.

### 2) 1 : N 일 경우

이 경우에는 유저 정보 조회시 연결된 동물에 대한 값은 배열 또는 1번과 동일하게 boolean값으로 할 수 있을 것 같습니다.
배열을 고려한 이유에는 처음 pet 정보 요청시 선택하기 위함이었습니다. 
그렇지 않은 경우에는 main pet이나 첫번째 등록 pet을 반환 하는 방법도 있다고 생각합니다.

#### 제안

개발 완성을 우선순위로 잡는 것을 잡아 API 구조는 1:1 을 기반으로 하는 것으로 만드는 것도 좋다고생각합니다.
아래의 사항들을 제안드립니다.
- 유저정보시에는 isResisterPet으로 불리언 값
- 1:! 관계일경우, 클라이언트에서는 petId를 알필요가 없기 떄문에 /pets 또는 /pet에서 펫정보를 반환
- 확장성을 고려한다면 /pets/${petId}, /pets 로 진행

## 추가 사항

로그인 유저를 기반으로 pet 정보를 조회하고 1 : N 관계가 아니라면 클라이언트에서는 petId 는 알지 않아도 되지 않을까 라는 생각이 들어 작성합니다.

**Comment by owonie** [comment]
좋은의견 감사합니다!

우선 말씀하신 펫과 유저의 관계에 대해서 얘기드리고자 합니다. 

기획명세서 상 펫과 유저의 관계는 일대다(1:n) 관계로 기재되어있습니다. 이는 여러명의 유저가 하나의 펫 정보만 바라보고있다는 점에서 알 수 있습니다. 저는 개인적으로 확장성을 고려했을 때, n:n 의 관계로 설계가 되는게 좋다는 의견에 동의합니다. 해당 사안은 개발 완성 이후에 확장하는 방향으로, 담이 말씀하신 제안대로 이행하면 좋을 듯 합니다.

isResisterPet 관련하여, 저도 유저정보 조회 api 기능 구현 시 고민을 했었는데요. 펫과 유저의 매칭 관계를 1:n 를 기준으로 설계할 때 petId 를 유저라는 객체의 속성 값으로 정해야할지 고민이 많았습니다. 한명의 유저는 한개 이하의 펫을 참조하고 있기에, 펫 정보를 조회할 수 있는 "키" 정도로 생각했었던 것 같아요. 

다만 말씀하신대로, 펫과 유저의 결합도를 낮추기 위해 hasPet / isResisteredPet과 같은 방식으로 처리해주고, 유저에게 등록된 펫 정보 조회를 원할 시 pet(또는 petlist) 와 같은 반환 값으로 api를 제공해주는 것이 좋아보이네요 :)

**Comment by owonie** [comment]
추가적으로 다음과 같이 기능추가 / 수정을 진행하도록 하겠습니다:
userInfo data:
hasPet 필드명을 클라이언트에 전달 -> getPetList로 펫 정보 조회 -> pet_list 데이터를 반환 받으며, pet_list에 main pet이라는 속성을 제공

혹시 필요한 수정사항 있다면 코멘트 달아주시면 감사하겠습니다 :)
